# CUDA
cuda_devices: '0'   # multi-gpu training is available

# dataset
dataset:
  data_path: '../data/Patches_noHole_and_collected.h5'
  in_point: 1024
  data_augmentation: true

# result
ckpt_root: '../ckpt/Res_GCN_improve_exp'

# Network
network:
  generator:
    k: 8
    feat_dim: 128
    res_conv_dim: 128
  discriminator:
    k: 8
    feat_dim: 64
    res_conv_dim: 64

loss:
  lambd: 5000

# train
seed: 0
phase: 'pre' #pre/gan
optimizer: 'adam' # adam
lr: 0.001
momentum: 0.9
weight_decay: 0.00001
batch_size: 24
max_epoch: 80
save_steps: 10

#scheduler: 'cos' # step/cos
#milestones: [30, 60, 90]
#gamma: 0.1
